# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Dropbox\Projects\Spectacle\Spectacle_Servo_Control_Board\Firmware\Spectacle_Servo_Control_Board\Spectacle_Servo_Control_Board.cydsn\Spectacle_Servo_Control_Board.cyprj
# Date: Tue, 13 Sep 2016 18:49:24 GMT
#set_units -time ns
create_clock -name {Clock_2(FFB)} -period 100.26041666666666 -waveform {0 50.1302083333333} [list [get_pins {ClockBlock/ff_div_4}]]
create_clock -name {EZI2C_SCBCLK(FFB)} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {UART_SCBCLK(FFB)} -period 729.16666666666663 -waveform {0 364.583333333333} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {Clock_1(FFB)} -period 2000 -waveform {0 1000} [list [get_pins {ClockBlock/ff_div_5}] [get_pins {ClockBlock/ff_div_6}] [get_pins {ClockBlock/ff_div_7}] [get_pins {ClockBlock/ff_div_8}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/hfclk}] -edges {1 5 9} -nominal_period 100.26041666666666 [list]
create_generated_clock -name {EZI2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 7 13} [list]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 35 71} [list]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 97 193} [list]


# Component constraints for C:\Dropbox\Projects\Spectacle\Spectacle_Servo_Control_Board\Firmware\Spectacle_Servo_Control_Board\Spectacle_Servo_Control_Board.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Dropbox\Projects\Spectacle\Spectacle_Servo_Control_Board\Firmware\Spectacle_Servo_Control_Board\Spectacle_Servo_Control_Board.cydsn\Spectacle_Servo_Control_Board.cyprj
# Date: Tue, 13 Sep 2016 18:49:20 GMT
